### PR TITLE
Launch Server settings if first launch

### PR DESCRIPTION
**Pull request by lakshyagupta21**
Fixes Issue [#1372](https://github.com/opendatakit/opendatakit/issues/1372)

### CODE REVIEW

**Comment by jbeorse** [comment]
runtests

**Comment by jbeorse** [comment]
runtests

**Comment by jbeorse** [comment]
When running this, the first time Services runs I am seeing a crash. I get the following error from Logcat:

```
03-06 06:01:15.643 24428-24428/org.opendatakit.services E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: org.opendatakit.services, PID: 24428
                                                                          java.lang.RuntimeException: Unable to resume activity {org.opendatakit.services/org.opendatakit.services.MainActivity}: java.lang.IllegalStateException: Unable to open properties lock file
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3558)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3598)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2830)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6351)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
                                                                           Caused by: java.lang.IllegalStateException: Unable to open properties lock file
                                                                              at org.opendatakit.properties.GainPropertiesLock.<init>(GainPropertiesLock.java:57)
                                                                              at org.opendatakit.properties.PropertiesSingleton.readProperties(PropertiesSingleton.java:632)
                                                                              at org.opendatakit.properties.PropertiesSingleton.init(PropertiesSingleton.java:458)
                                                                              at org.opendatakit.properties.PropertiesSingleton.<init>(PropertiesSingleton.java:120)
                                                                              at org.opendatakit.properties.PropertiesSingletonFactory.getSingleton(PropertiesSingletonFactory.java:77)
                                                                              at org.opendatakit.properties.CommonToolProperties.get(CommonToolProperties.java:300)
                                                                              at org.opendatakit.services.MainActivity.onResume(MainActivity.java:113)
                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
                                                                              at android.app.Activity.performResume(Activity.java:6879)
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3535)
```

**Comment by lakshyagupta21** [comment]
I tried running it in real device everything seems fine in my device.

**Comment by jbeorse** [comment]
To repro, I have installed Survey, Tables, and Services on my device. I then ran `grunt adbpush` in the app-designer directory to push app files. I then launch Services for the first time and it prompts me to grant permissions. After I do, or before sometimes, it will crash.

Which version of Android are you using? I am on Android 7. You might try a device or emulator on Android 6 or 7 and see if those still work.

**Comment by lakshyagupta21** [comment]
@jbeorse Sorry, I didn't test it well actually, I was trying to access storage before permissions are granted.
And it was giving some build errors before due to the constants that I used here which I've added in androidlibrary.   

I've modified the code please review.

**Comment by jbeorse** [comment]
This fixed the issue for me. Thanks. The switch to the new permission model does introduce a lot of tricky issues like this.

It is looking great so far. My only issue is that on this first launch it puts the user in Server Settings but doesn't notify the user why this is happening. It seems like this could be confusing. In my opinion there should be a dialog box that displays on the first launch and asks the user "Do you want to configure the server settings now?" or something like that. The user can either click "yes" and set up the server settings or click "no" and stay on the main page. Basically only run these lines if the user clicks yes:
```
Intent intent = new Intent( this, AppPropertiesActivity.class );
intent.putExtra( PreferenceActivity.EXTRA_SHOW_FRAGMENT, ServerSettingsFragment.class.getName() );
intent.putExtra( PreferenceActivity.EXTRA_NO_HEADERS, true );
startActivity(intent);
```

Moving the permissions check to onResume seems safe to me. However, I want to double check with @linl33 who originally wrote them. @linl33, are there any surprise issues or performance problems with checking permissions in onResume instead of onCreate?

**Comment by lakshyagupta21** [comment]
@jbeorse @linl33  There was some problem created by moving permissions check to onResume, I've added a check to make sure it doesn't create a problem of asking it again and again, actually when you tap on `deny` then it again asks for the problem and so on.
A dialog is also added to notify the user before navigating to server settings.

**Comment by linl33** [comment]
@lakshyagupta21 
I found 2 problems, 
1. If you launch Tables/Survey before Services, you don't get the dialog prompting for server configuration.  
This is because Tables and Survey launch Services to allow the user to grant Services the necessary permissions, and that caused the first launch property to incorrectly be set to false. My suggestion for this would be to move the dialog and first launch check into the sync activity. In my opinion it makes more sense to ask for server configuration there and it would also solve this problem. Also this would make the permission request logic a bit simpler. 

2. After sync, the dialog prompting for server configuration shows up again.  
This is because the `services.first_launch` property is stored in general properties. After a sync, the general property get overwritten by the server's version and the missing fields populated by the default value.

**Comment by lakshyagupta21** [comment]
@linl33 
I am able to reproduce both the problems, and I've modified the code in androidlibrary which stores `services.first_launch` in device properties and it works fine now. Will there be any issue if it gets stored in device properties?

**Comment by linl33** [comment]
deviceProperties sounds good

**Comment by wbrunette** [comment]
runtests

**Comment by jbeorse** [comment]
This looks good to me.  Thanks for your hard work on this!

Please remove the whitespace changes to MainActivity and I'll merge it.

**Pull request merged**
