### PR TITLE
Bring back Remove incorrect inheritance	

### PR DESCRIPTION
**Pull request by nilesr**
Needs to be accepted with the same pr in androidlibrary

### CODE REVIEW

**Comment by nilesr** [comment]
https://github.com/opendatakit/androidlibrary/pull/17

**Comment by jbeorse** [comment]
Can one of the admins verify this patch?

**Comment by jbeorse** [comment]
Can one of the admins verify this patch?

**Comment by wbrunette** [comment]
runtests

**Comment by wbrunette** [comment]
runtests

**Pull request closed without merging**
