### PR TITLE
Validate table health before changing authentication

### PR DESCRIPTION
**Pull request by jbeorse**
When a user enters the login screen or the server settings page, this change will check to see if there are any unsynced changes and if there are any conflicts or checkpoints. If there are unsynced changes, the user will be prompted to sync their changes or ignore the unsynced changes at their own risk. If there are conflicts and/or checkpoints, the normal conflict and checkpoint resolution activities will be launched. 

This pull request is a prerequisite: https://github.com/opendatakit/androidlibrary/pull/10

### CODE REVIEW

**Comment by nilesr** [comment]
So is it the exact same code in LoginFragment and ServerSettingsFragment? If so, we should probably leave comments around it letting people know that if they change one, they should also change the other

**Comment by jbeorse** [comment]
That's a fair point. It is basically a copy paste. I had hoped to abstract it out into a shared util but it is mostly made up of UI code that needs to live in the Activity or Fragment itself. I'm open to suggestions in how to properly abstract this. Otherwise I'll push a comment as Niles suggests

**Comment by jbeorse** [comment]
I've made Niles's suggested changes

**Comment by mitchellsundt** [comment]
Looks good

**Comment by nilesr** [comment]
It looks like this introduced a bug, going to server settings now causes a crash

	07-24 12:16:45.133 22499-22499/? E/AndroidRuntime: FATAL EXCEPTION: main
   Process: org.opendatakit.services, PID: 22499
   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.opendatakit.services/org.opendatakit.services.preferences.activities.AppPropertiesActivity}: java.lang.IllegalStateException: OdkConnectionFactorySingleton not yet initialized! If this happens then configure must be called
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	   at android.app.ActivityThread.-wrap11(ActivityThread.java)
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	   at android.os.Handler.dispatchMessage(Handler.java:102)
	   at android.os.Looper.loop(Looper.java:148)
	   at android.app.ActivityThread.main(ActivityThread.java:5417)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	Caused by: java.lang.IllegalStateException: OdkConnectionFactorySingleton not yet initialized! If this happens then configure must be called
	   at org.opendatakit.services.database.OdkConnectionFactorySingleton.getOdkConnectionFactoryInterface(OdkConnectionFactorySingleton.java:34)
	   at org.opendatakit.services.utilities.TableHealthValidator.verifyTableHealth(TableHealthValidator.java:68)
	   at org.opendatakit.services.preferences.fragments.ServerSettingsFragment.onCreate(ServerSettingsFragment.java:311)
	   at android.app.Fragment.performCreate(Fragment.java:2198)
	   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
	   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	   at android.app.BackStackRecord.run(BackStackRecord.java:793)
	   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	   at android.app.FragmentController.execPendingActions(FragmentController.java:325)
	   at android.app.Activity.performStart(Activity.java:6267)
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
	   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
	   at android.os.Handler.dispatchMessage(Handler.java:102) 
	   at android.os.Looper.loop(Looper.java:148) 
	   at android.app.ActivityThread.main(ActivityThread.java:5417) 
	   at java.lang.reflect.Method.invoke(Native Method) 
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Pull request merged**
