### PR TITLE
Bring back Fix a bad null pointer check that was causing all the data…

### PR DESCRIPTION
**Pull request by nilesr**
…base tests to fail

### CODE REVIEW

**Comment by jbeorse** [comment]
Can one of the admins verify this patch?

**Comment by jbeorse** [comment]
Can one of the admins verify this patch?

**Comment by jbeorse** [comment]
runtests

**Comment by jbeorse** [comment]
runtests

**Comment by jbeorse** [comment]
runtests

**Comment by wbrunette** [comment]
runtests

**Comment by wbrunette** [comment]
runtests

**Pull request closed without merging**
