### PR TITLE
Fixes app crashing while opening a browser

### PR DESCRIPTION
**Pull request by MajidSas**
This pull request fixes this issue https://github.com/opendatakit/opendatakit/issues/1384

The intent is created and handled in the onHeaderClick in AppPropertiesActivity.java.
If the exception is raised a new webView activity is started showing the website.

### CODE REVIEW

**Comment by wbrunette** [comment]
runtests

**Comment by wbrunette** [comment]
Since ODK2 makes heavy use of webviews, the name WebViewActivity might add to confusion of what each part of the code is meant for. Perhaps rename it AboutWebViewActivity or something similar to reduce confusion for future developers..

**Comment by jbeorse** [comment]
runtests

**Comment by jbeorse** [comment]
Hi @MajidSas. Thanks for working on this issue! I have to admit, I'm having trouble reproducing the original error, which means I can't test your code. Where are you finding an Android version without a browser installed? Is there a way to uninstall the browser from the emulator?

**Comment by MajidSas** [comment]
I tested it on API 23 and API 25. The issue is not present on API 25 even if no browser is installed. The system automatically creates a new WebView. For API 23, I disabled the default browser in the settings, and then the issue was reproduced.
This image shows that the default browser in Android API 23 is disabled: https://imgur.com/a/CDHUK

**Comment by jbeorse** [comment]
Thanks for the heads up. I was able to reproduce the error and verify your code.

Instead of hard coding the URL "http://opendatakit.org" please create an entry in strings.xml and reference that.

**Comment by jbeorse** [comment]
@MajidSas that is good, though you've got one more in line 295 of AppPropertiesActivity.

**Comment by jbeorse** [comment]
runtests

**Pull request merged**
